version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: deveen-company-profile
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
    ports:
      - "5000:80"
